CREATE DATABASE Store


CREATE TABLE CUSTOMER
(
ID INT IDENTITY(1,1) PRIMARY KEY,
Name VARCHAR(255) NOT NULL,
Email VARCHAR(255) NOT NULL UNIQUE,
Address VARCHAR(255) NOT NULL,
Phone Varchar(20) NOT NULL
);
INSERT INTO CUSTOMER VALUES('João Silva', 'joao.silva@example.com', 'Rua dos Examples, 123', '555-1234');

INSERT INTO CUSTOMER VALUES('Emmylly Santos', 'Emmylly.santos@example.com', 'Avenida das Amostras, 456', '555-5678');

INSERT INTO CUSTOMER VALUES('Maria De nazaré', 'maria.naza@example.com', 'Avenida Eptacio, 421', '523-0987');


INSERT INTO CUSTOMER VALUES(' Ze Gabriel', 'zezinho.biel@example.com', 'Rua zé, 456', '123-5678');


select * from CUSTOMER


CREATE TABLE PRODUCT
(
ID INT IDENTITY(1,1) PRIMARY KEY,
NAME VARCHAR(255) NOT NULL,
DESCRIPTION TEXT ,
PRICE NUMERIC(10,2) NOT NULL,
QUANTITY INT NOT NULL

);

INSERT INTO PRODUCT (NAME, DESCRIPTION, PRICE, QUANTITY)
VALUES ('PLAYSTATION 4', 'Market launch, 1TB HDD, thermal efficiency', 100, 99);

INSERT INTO PRODUCT (NAME, DESCRIPTION, PRICE, QUANTITY)
VALUES ('JBL Phone', 'Market Launch, jbl520 Phone', 1000, 500);

INSERT INTO PRODUCT (NAME, DESCRIPTION, PRICE, QUANTITY)
VALUES ('JBL Headset', 'Market Launch, Bluetooth Headset 720', 2000, 99);

INSERT INTO PRODUCT (NAME, DESCRIPTION, PRICE, QUANTITY)
VALUES ('XBox One', 'Release 2023, The best Xbox ever', 2200, 99);

INSERT INTO PRODUCT (NAME, DESCRIPTION, PRICE, QUANTITY)
VALUES ('XBox series x', 'Release 2024, Worlds best Xbox', 2200, 99);

select * from PRODUCT


CREATE TABLE Stock
(
ID INT IDENTITY(1,1) PRIMARY KEY,
PRODUCT_ID INT NOT NULL,
FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (ID),
QUANTITY INT NOT NULL
);

INSERT INTO Stock (PRODUCT_ID, QUANTITY)
VALUES (1, 99);

INSERT INTO Stock (PRODUCT_ID, QUANTITY)
VALUES (2, 500);

INSERT INTO Stock (PRODUCT_ID, QUANTITY)
VALUES (3, 200);


INSERT INTO Stock (PRODUCT_ID, QUANTITY)
VALUES (4, 250);


INSERT INTO Stock (PRODUCT_ID, QUANTITY)
VALUES (5, 400);



CREATE TABLE SALE

(
ID INT IDENTITY(1,1) PRIMARY KEY,
CUSTOMER_ID INT NOT NULL,
FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER (ID),
DATE TIMESTAMP NOT NULL DEFAULT,
AMOUNT NUMERIC(10,2) NOT NULL
);


INSERT INTO SALE (CUSTOMER_ID, AMOUNT)
VALUES (1, 100.00);

INSERT INTO SALE (CUSTOMER_ID, AMOUNT)
VALUES (2, 250.00);

INSERT INTO SALE (CUSTOMER_ID, AMOUNT)
VALUES (3, 150.00);

INSERT INTO SALE (CUSTOMER_ID, AMOUNT)
VALUES (4, 75.50);

select * from SALE


